version: '3'
services:
  database:
    container_name: database
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - /home/jhordycg/mysql/conf:/etc/mysql/conf.d
    env_file:
      - database-mysql.env
volumes:
  dbdata:
